# Backup arguments
global:
  cnpgBackup:
    enabled: false
#     accessKey: <accessKey>
#     secretKey: <secretKey>
#     endpointURL: # https://s3.backup.nas.athome:9000
#     destinationPath: # s3://cnpg/athome
#     retentionPolicy: 30d

# Database name
name: ""

# Specific container image to use
imageName: ""

# Number of instances, must be odd number
instances: 3

# Additional arguments to the initdb statement
initdb:
  postInitApplicationSQL: []
    # - ALTER SYSTEM SET search_path TO "$user", public, vectors;
    # - SET search_path TO "$user", public, vectors;
    # - CREATE EXTENSION IF NOT EXISTS "vectors";
  extraArgs: {}
    # dataChecksums: true

# Additional postgres configuration
config:
  sharedPreloadLibraries: []
    # - vchord.so

# Storage control for the cnpg cluster
storage:
  storageClass: "" #personal
  size: 1Gi
