# Name of the service
name: "authentik"
# Service to proxy to; with port
backend: <serice>:<port>
# Authentik outpost
outpost: ""

replicaCount: 1

# Proxy Image settings
image:
  repository: caddy
  tag: 2-alpine
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 30m
    memory: 100Mi
  requests:
    cpu: 15m
    memory: 50Mi