apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-auth-proxy-config" .Values.name }}
  labels:
    {{- include "authentik.selectorLabels" . | nindent 6 }}
data:
  Caddyfile: |
    :2080 {
        # always forward outpost path to actual outpost
        reverse_proxy /outpost.goauthentik.io/* {{ .Values.outpost }}

        # forward authentication to outpost
        forward_auth {{ .Values.outpost }} {
            uri /outpost.goauthentik.io/auth/caddy

            # capitalization of the headers is important, otherwise they will be empty
            copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

            # optional, in this config trust all private ranges, should probably be set to the outposts IP
            trusted_proxies private_ranges
        }

        # actual site configuration below, for example
        reverse_proxy {{ tpl .Values.backend . }}
    }