apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-auth" .Values.name }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
    - hosts:
        - {{ tpl .Values.ingress.host . }}
      secretName: {{ printf "%s-cert" .Values.name }}
  rules:
    - host: {{ tpl .Values.ingress.host . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-auth" .Values.name }}
                port:
                  name: http