apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-auth" .Values.name }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "authentik.selectorLabels" . | nindent 4 }}
