apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ printf "%s-db" .Values.name }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.instances }}
  {{- with .Values.imageName }}
  imageName: {{ . }}
  {{- end }}
  superuserSecret:
    name: {{ printf "%s-db-superuseruser" .Values.name }}
  bootstrap:
    initdb:
      database: {{ printf "%s-db" .Values.name }}
      owner: {{ .Values.name }}
      secret:
        name: {{ printf "%s-db-user" .Values.name }}
      {{- with .Values.initdb.postInitApplicationSQL }}
      postInitApplicationSQL:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.initdb.extraArgs }}
      {{- range $k, $v := . }}
      {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
{{- if .Values.global.cnpgBackup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.global.cnpgBackup.destinationPath }}
      endpointURL: {{ .Values.global.cnpgBackup.endpointURL }}
      endpointCA: 
        key: ca.crt
        name: app-inter-ca
      s3Credentials:
        accessKeyId:
          name: cnpg-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup
          key: ACCESS_SECRET_KEY
    retentionPolicy: {{ .Values.global.cnpgBackup.retentionPolicy | quote }}
{{- end }}
  storage:
    {{- with .Values.storage }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
