apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-superuser" .Values.name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: postgres
  password: {{ randAlphaNum 16 | quote }}
